## Address proxy will bind to.
proxy:
  host: 127.0.0.1
  port: 19122
## Destination server which the client will connect to.
## You are only able to join offline mode servers
destination:
  host: 127.0.0.1
  port: 19132
## Encode and decode packets to test protocol library for bugs
packet-testing: false
## Log packets for each session
log-packets: true
## Where to log packet data
## Valid options: console, file or both
log-to: file
## If the proxy should extract and save version data into the data folder
export-data: false

## Packets to ignore to make your log more refined. These default packet are generally spammed
ignored-packets:
  - "NetworkStackLatencyPacket"
  - "LevelChunkPacket"
  - "MovePlayerPacket"
  - "PlayerAuthInputPacket"
  - "NetworkChunkPublisherUpdatePacket"
  - "ClientCacheBlobStatusPacket"
  - "ClientCacheMissResponsePacket"
  - "MoveEntityDeltaPacket"
  - "SetEntityMotionPacket"
  - "SetEntityDataPacket"
  - "AddEntityPacket"
  - "UpdateBlockPacket"
  - "SetTimePacket"
  - "EntityEventPacket"
  - "InventoryContentPacket"
  - "BiomeDefinitionListPacket"
  - "CreativeContentPacket"
  - "AvailableEntityIdentifiersPacket"
  - "CraftingDataPacket"
  - "AvailableCommandsPacket"
